### ISSUE TITLE
Wrong dimension of states in Miner-Testing-CodeSample

### ISSUE THREAD

**Issue by hai-h-nguyen** [xphongvn/rlcomp2020#7] opened 2020-08-03 03:40 UTC
Hi, 

It seems that the dimension of the return states is not always 198. I fix the action of the DQN agent to be 4 (rest) and the size of the return states will be 196 which is incorrect.

**Comment by thotho** [comment] 2020-08-03 08:44
Could you tell us, how you updated the code (in details)?

**Comment by hai-h-nguyen** [comment] 2020-08-03 12:51
I simply override "action = np.argmax(DQNAgent.predict(s.reshape(1, len(s))))" with action = 4.

**Comment by thotho** [comment] 2020-08-04 04:31
Is your code as below?
```
action = 4
#action = np.argmax(DQNAgent.predict(s.reshape(1, len(s))))  # Getting an action from the trained model
```
If yes, I confirmed there are no problems with the code.
Maybe you have updated something else.
If you need more support, please do not hesitate to contact us directly.
Thanks,

**Comment by hai-h-nguyen** [comment] 2020-08-04 13:10
I think its still wrong. See the latest pull request from someone else.

**Comment by thotho** [comment] 2020-08-05 02:47
That is not a bug, we won't merge the request to master.
If you wan to change training model to use other info of players, you can do same as the commit.
But for the sample, we don't need to do that.
For your problem of state dimension, if you need more support, please contact us directly.
Thanks,

**Comment by thotho** [comment] 2020-08-05 03:01
This is not a bug, and we won't merge the pull request to master (You can see my comments in the commits)
For you problem of state dimension, please contact us directly if you need more support.

**Comment by datvtn** [comment] 2020-08-05 18:11
mình cũng đang gặp issue này tại phần test khi train thử model của BTC rồi chạy test khi len của get_state là 198 khi train và trong khi test là 4

**Comment by hvt1609** [comment] 2020-08-06 01:52
I think it had fixed. You try pull the new version. Note that you must run server first : Miner-Testing-Server/DUMMY_SERVER.py

**Comment by thotho** [comment] 2020-08-06 03:34
Sorry for late reply.
Yesterday, we have merged a pull request to fix the bug of state dimension.
Please pull the code and check if this fix your problem.
(Actually, I wrote a comment to inform you about this, but I don't know why the comment is not posted)

**Comment by culi9x** [comment] 2020-08-06 04:35
> I think its still wrong. See the latest pull request from someone else.

I think it's because in the Initialize environment, self.players does't have information of "playerId1". You can use my code in Pull requests to fix it.

**Comment by thotho** [comment] 2020-08-06 10:49
The bug happens when you train without bots, and one of dummy players has same ID with your agent's ID (1).
This has been fixed in the last merge request, then I will close this issue.
Thank for your report.

**Closed as completed by thotho** 2020-08-06 10:49 UTC
